{{ if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Chart.Name }}
      minAllowed:
        cpu: "200m"
        memory: "300Mi"
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name:  {{ .Values.name }}
  updatePolicy:
    updateMode: Auto
{{ end }}
