# Default values for name: k8s-dns-node-cache-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: aws-cloud-controller-manager
serviceType: managed

image:
  registry: gsoci.azurecr.io
  name: giantswarm/aws-cloud-controller-manager
  tag: v1.27.6

# We set the limit twice as the requests so that the VPA
# can keep the ratio when scaling
resources:
  limits:
    cpu: 400m
    memory: 600Mi
  requests:
    cpu: 50m
    memory: 75Mi

ports:
  healthcheck: 10267

test:
  image:
    name: giantswarm/alpine-testing
    tag: 0.1.1

verticalPodAutoscaler:
  enabled: true
  minAllowed:
    cpu: 50m
    memory: 50Mi

# set the HTTP_PROXY, HTTPS_PROXY and NO_PROXY variable
proxy:
  noProxy:
  http:
  https:
cluster:
  # is getting overwritten by the top level proxy if set
  # These values are generated via cluster-apps-operator
  proxy:
    noProxy:
    http:
    https:

# These values set the `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` environment variables.
# These are useful when installing the controller without CNI or kube-proxy and we need to find an alternative way for the controller to talk to the k8s API.
k8sServiceHost: ""
k8sServicePort: ""

global:
  podSecurityStandards:
    enforced: false
