# Default values for name: k8s-dns-node-cache-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: aws-cloud-controller-manager
serviceType: managed

image:
  registry: quay.io
  name: giantswarm/aws-cloud-controller-manager
  tag: v1.22.4

resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 200m
    memory: 300Mi

ports:
  healthcheck: 10267

test:
  image:
    name: giantswarm/alpine-testing
    tag: 0.1.1

verticalPodAutoscaler:
  enabled: true
